### PR TITLE
Fix: take yield data from ch0 instead of the last channel

### PR DESCRIPTION
**Pull request by ZsZs73**
Hello Marcel,
Thanks for creating the ESP version of the AHOY.
This PR is:
- fixing the inverter yield_total and yield_daily as the original version takes it from the last channel. It works with a single channel inverter but gives haf/quarter amount in case the inverter has 2/4 channels. The fix takes the accumulated value from ch0.
- cosmetic fix: rename yield_temperature_sensor to teperature_sensor
- align some accuracy_decimal values to the accuracy provided by the inverter

### CODE REVIEW

**Comment by a-marcel** [comment]
Hello, thanks for your PR. Somehow i was missing the notification and the code base change a lot. I adjust your PR to the new structure and added your changes to the new places. Thanks for checking multi channel devices - i only use the HM400 that has only one channel.

Btw: Limiting as well as on/off is part of the code now too.

**Comment by a-marcel** [comment]
Could you tell me what version of ESP and inverter you use ? I would like to add this to the README file, that this esphome version was tested with that devices. Thanks

**Comment by ZsZs73** [comment]
Hello,
Actually I made your initial version work once on a Wemos D1 mini clone (ESP8266).
To make it work I had to hardcode the inverter serial number to the `hoymiles_component.cpp` as follows:
`mSys->addInverter(this->inverters_[i].identification_, 12345789012345, modPwr);`
where `12345789012345` is the serial number of the inverter converted to decimal number, otherwise the serial number was always set to 0xFFFFFFFF according to the ESP cosnole.

Then I started tinkering with the changes I made for the PR.  Then somehow I managed to get to a state where the code does not transmit any packets via the radio.
I decided to buy an ESP32 to try the code on the platform where you developed it.
The board I bought is an az-delivery ESP32 D1 mini.

Fast-forward to this week: after I saw you new commits I compiled it for the ESP32 and I found that simply setting the serial number like in your example, it get accepted by the code. However the issue that it does not transmit anything persist. Sometimes I see packets received by the radio: I have an another ESP8266 running the code from the forum: 0.4.25.
This works, but it is instable. It loses the connection to the mqtt server and does not reconect.
I have to manually reboot it.

Honestly I'd prefer to have the ESPhome version as ESPhome in general is quite stable and there is no need to hassle with mqtt retry mechanisms as ESPhome handles the communication to HA natively.

BTW I have a two channel HM800 inverter.

edit: typos

**Comment by a-marcel** [comment]
Hello, not sure if i understand your message. Are you saying it works for you or not ? this morning, i synced the code from ahoy into this project. Maybe this is more stable for you.

**Comment by ZsZs73** [comment]
Hello, unfortunately I can not make it work. Would you please support me via some IM?
It must be something trivial I am doing wrong.
I can compile the code, the RF module seems ok, but still no transmits according to the log.

**Comment by ZsZs73** [comment]
Hello, I've noticed a new update with the simplified serial number in the yaml file.
I've pulled this update, but I still do not see any transmits in the logs.
However if I change the log level to VERBOSE, then I see following messages in the log:
```09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload
09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload
09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload
09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload
09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload
09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload
09:58:21 | [V] | [hoymiles.esp32:330] | app::processPayload`

Is this expected?

**Comment by a-marcel** [comment]
Hello, this messages are from the original ahoy version and expected. But this would also mean, that you have a payload from your hoymiles.

What i think (and i gave this hint already to someone else). could you configure an NTP Server in your esphome ? 

```
time:
  - platform: sntp
    id: hoymiles_time
```

I currently debug an issue with my own setup/hardware and i think there is an issue with the time in the code.

**Comment by ZsZs73** [comment]
Hello, thanks for getting back to me.
I've already tried with both time sources:

```
time:
  - platform: sntp
    id: hoymiles_time
```
and
```
time:
  - platform: homeassistant
    id: homeassistant_time
```
If I set the later then I see the following in the log:
```
[10:24:03][D][api.connection:861]: Home Assistant 2022.4.7 (::FFFF:C0BB:606): Connected successfully
[10:24:03][D][time:042]: Synchronized time: 2022-08-08 10:24:03
```
In case of NTP there is no 'Synchronized time:' message for a couple of minutes for sure, however I see the NTP request and response passing the firewall.

**Comment by a-marcel** [comment]
I committed a new version that fixes (maybe) a timestamp issue. And so far i didn't understand your issue yet - what problem do you have ? Thanks

**Comment by ZsZs73** [comment]
I am sorry to make you confused.
Please ignore all the above and I am trying to summarize the situation with my ESP32.
- the code I pulled from you git compiles
- the nRF module seems to be connected
- the NRF module does not poll the inverter, at least there are no transmit messages on the console
I'd like to share my config and detailed logs but preferrably not here.
In case you have telegram, please search for my github username.

**Pull request merged**
